language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: '5fa32cd2-9037-44c4-b3cf-ffd982fb70ab'
  app: when-app
  on:
    repo: HarrisJW/When
env:
- secure: d5e0d7b5-01d5-4098-bf5d-95550c9f2360